import type { PluginModule, PluginExecutionContext } from '@runflux/plugin-system/types';

export const manifest: PluginModule['manifest'] = {
  id: 'trigger-webhook',
  name: 'Webhook Trigger',
  category: 'trigger',
  version: '1.0.0',
  parameters: [
    {
      name: 'path',
      label: 'Webhook Path',
      type: 'string',
      required: true,
      default: '/webhook',
    },
    {
      name: 'httpMethod',
      label: 'HTTP Method',
      type: 'string',
      required: true,
      default: 'POST',
    },
    {
      name: 'auth',
      label: 'Authentication Mode',
      type: 'string',
      required: false,
      default: 'none',
    },
    {
      name: 'secretEnvVar',
      label: 'Secret Environment Variable Name',
      type: 'string',
      required: false,
      default: 'WEBHOOK_SECRET',
    },
    {
      name: 'sampleBody',
      label: 'Sample Simulation Body (Canvas Testing)',
      type: 'json',
      required: false,
      default: { message: 'Sample webhook payload' },
    },
    {
      name: 'sampleHeaders',
      label: 'Sample Headers',
      type: 'json',
      required: false,
      default: { 'content-type': 'application/json' },
    },
    {
      name: 'sampleQuery',
      label: 'Sample Query Params',
      type: 'json',
      required: false,
      default: {},
    },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['main'],
};

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => {
    const path = (nodeConfig.path as string) || '/webhook';
    const method = ((nodeConfig.httpMethod as string) || 'POST').toUpperCase();
    const auth = (nodeConfig.auth as string) || 'none';
    const secretEnvVar = (nodeConfig.secretEnvVar as string) || 'WEBHOOK_SECRET';

    return {
      files: [
        {
          path: 'trigger-webhook.ts',
          content: `// Generated by RunFlux for plugin "trigger-webhook"
export const WEBHOOK_PATH = ${JSON.stringify(path)};
export const WEBHOOK_METHOD = ${JSON.stringify(method)};
export const WEBHOOK_AUTH = ${JSON.stringify(auth)};
export const WEBHOOK_SECRET_ENV = ${JSON.stringify(secretEnvVar)};

export function run(input: any) {
  if (input && typeof input === 'object' && ('body' in input || 'headers' in input || 'query' in input)) {
    return input;
  }
  return {
    body: input ?? {},
    headers: {},
    query: {},
    path: WEBHOOK_PATH,
    method: WEBHOOK_METHOD,
    receivedAt: new Date().toISOString(),
  };
}
`,
        },
      ],
      infra: [],
    };
  },
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
};

export const execute: PluginModule['execute'] = (params, input, _context?: PluginExecutionContext) => {
  const reqInput = input && typeof input === 'object' ? (input as Record<string, unknown>) : null;

  const body = reqInput?.body ?? params.sampleBody ?? { message: 'Sample webhook payload' };
  const headers = reqInput?.headers ?? params.sampleHeaders ?? { 'content-type': 'application/json' };
  const query = reqInput?.query ?? params.sampleQuery ?? {};

  return {
    body,
    headers,
    query,
    method: (params.httpMethod as string) || 'POST',
    path: (params.path as string) || '/webhook',
    receivedAt: new Date().toISOString(),
  };
};
