import type { PluginModule, PluginExecutionContext } from '@runflux/plugin-system/types';
import { FIELDS_ROW_SCHEMA, composeFields, type FieldConfig } from '@runflux/plugin-system/fields-row-schema';

export const manifest: PluginModule['manifest'] = {
  id: 'trigger-webhook',
  name: 'Webhook Trigger',
  category: 'trigger',
  version: '1.0.0',
  parameters: [
    {
      name: 'path',
      label: 'Webhook Path',
      type: 'string',
      required: true,
      default: '/webhook',
    },
    {
      name: 'httpMethod',
      label: 'HTTP Method',
      type: 'string',
      required: true,
      default: 'POST',
    },
    {
      name: 'authentication',
      label: 'Authentication Mode',
      type: 'string',
      required: false,
      default: 'none',
    },
    {
      name: 'headerName',
      label: 'Header Name',
      type: 'string',
      required: false,
      default: 'X-Webhook-Secret',
    },
    {
      name: 'secretEnvVar',
      label: 'Secret Environment Variable Name',
      type: 'string',
      required: false,
      default: 'WEBHOOK_SECRET',
    },
    {
      name: 'rawBody',
      label: 'Accept Any / Raw Body',
      type: 'boolean',
      required: false,
      default: false,
    },
    {
      name: 'sampleBody',
      label: 'Sample Simulation Body (Fallback)',
      type: 'json',
      required: false,
      default: [{ name: 'message', value: 'Sample webhook payload', type: 'string' }],
      rowSchema: FIELDS_ROW_SCHEMA,
    },
    {
      name: 'sampleHeaders',
      label: 'Sample Headers',
      type: 'json',
      required: false,
      default: { 'content-type': 'application/json' },
    },
    {
      name: 'sampleQuery',
      label: 'Sample Query Params',
      type: 'json',
      required: false,
      default: {},
    },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['main'],
};

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => {
    const path = (nodeConfig.path as string) || '/webhook';
    const method = ((nodeConfig.httpMethod as string) || 'POST').toUpperCase();
    const auth = (nodeConfig.authentication as string) || (nodeConfig.auth as string) || 'none';
    const headerName = (nodeConfig.headerName as string) || 'X-Webhook-Secret';
    const secretEnvVar = (nodeConfig.secretEnvVar as string) || 'WEBHOOK_SECRET';
    const rawBody = Boolean(nodeConfig.rawBody);

    return {
      files: [
        {
          path: 'trigger-webhook.ts',
          content: `// Generated by RunFlux for plugin "trigger-webhook"
export const WEBHOOK_PATH = ${JSON.stringify(path)};
export const WEBHOOK_METHOD = ${JSON.stringify(method)};
export const WEBHOOK_AUTH = ${JSON.stringify(auth)};
export const WEBHOOK_HEADER_NAME = ${JSON.stringify(headerName)};
export const WEBHOOK_SECRET_ENV = ${JSON.stringify(secretEnvVar)};
export const WEBHOOK_RAW_BODY = ${JSON.stringify(rawBody)};

export function run(input: any) {
  const request = input && typeof input === 'object' ? input : {};
  const body = request.body !== undefined ? request.body : input;
  const value = body && typeof body === 'object' && !Array.isArray(body)
    ? { ...body, _headers: request.headers ?? {}, _query: request.query ?? {} }
    : { data: body, _headers: request.headers ?? {}, _query: request.query ?? {} };
  return { value, activeOutput: 'main' };
}
`,
        },
      ],
      infra: [],
    };
  },
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
};

export interface PendingWebhook {
  path: string;
  resolve: (data: any) => void;
  reject: (err: any) => void;
  timer: any;
}

function getGlobalPendingWebhooks(): PendingWebhook[] {
  const g = globalThis as any;
  if (!g.__RUNFLUX_PENDING_WEBHOOKS__) {
    g.__RUNFLUX_PENDING_WEBHOOKS__ = [];
  }
  return g.__RUNFLUX_PENDING_WEBHOOKS__;
}

export function pushTestWebhook(targetPath: string, payload: any): boolean {
  const list = getGlobalPendingWebhooks();
  if (list.length === 0) {
    return false;
  }

  const cleanTarget = targetPath.replace(/^\/+/, '').toLowerCase();

  let idx = list.findIndex((p) => {
    const cleanP = (p.path || '').replace(/^\/+/, '').toLowerCase();
    return cleanP === cleanTarget || cleanP === '*' || cleanTarget.endsWith(cleanP) || cleanP.endsWith(cleanTarget);
  });

  if (idx === -1 && list.length > 0) {
    idx = 0;
  }

  if (idx !== -1) {
    const pending = list.splice(idx, 1)[0];
    clearTimeout(pending.timer);
    pending.resolve(payload);
    return true;
  }

  return false;
}

export function clearPendingWebhooks(): void {
  const list = getGlobalPendingWebhooks();
  while (list.length > 0) {
    const p = list.pop();
    if (p) {
      clearTimeout(p.timer);
      p.reject(new Error('Webhook listener cancelled'));
    }
  }
}

function formatWebhookOutput(body: any, headers: any, query: any) {
  if (typeof body === 'object' && body !== null && !Array.isArray(body)) {
    return {
      ...body,
      _headers: headers ?? {},
      _query: query ?? {},
    };
  }
  return {
    data: body,
    _headers: headers ?? {},
    _query: query ?? {},
  };
}

/**
 * `sampleBody` is declared with `rowSchema: FIELDS_ROW_SCHEMA` (same shape as `set`'s
 * `fields`), so it's authored as an array of named, typed rows — compose those into
 * the flat object the simulated `$json` should actually look like. A plain object is
 * still accepted as-is (a caller passing a literal sample body directly).
 */
function resolveSampleBody(sampleBody: unknown): unknown {
  if (Array.isArray(sampleBody)) return composeFields(sampleBody as FieldConfig[]);
  if (sampleBody !== null && typeof sampleBody === 'object') return sampleBody;
  return { message: 'Sample webhook payload' };
}

export const execute: PluginModule['execute'] = async (params, input, context?: PluginExecutionContext) => {
  const reqInput = input && typeof input === 'object' ? (input as Record<string, unknown>) : null;

  // 1. If payload was already provided from upstream caller:
  if (reqInput && ('body' in reqInput || 'headers' in reqInput || 'query' in reqInput)) {
    return { value: formatWebhookOutput(reqInput.body, reqInput.headers, reqInput.query), activeOutput: 'main' };
  }

  // 2. If running under automated unit tests without explicit waiting mode, return sample body:
  if (process.env.NODE_ENV === 'test' && !process.env.RUNFLUX_WAIT_WEBHOOK_TEST) {
    const body = resolveSampleBody(params.sampleBody);
    return { value: formatWebhookOutput(body, params.sampleHeaders ?? {}, params.sampleQuery ?? {}), activeOutput: 'main' };
  }

  // 3. User interactive test in canvas: wait for an actual HTTP request to arrive!
  const path = ((params.path as string) || '/webhook').trim();
  const normalizedPath = path.startsWith('/') ? path : `/${path}`;
  const timeoutMs = 120000;

  const list = getGlobalPendingWebhooks();

  return new Promise((resolve, reject) => {
    let settled = false;

    // Whichever of timeout / real delivery / explicit cancel (clearPendingWebhooks) /
    // this run's own abort signal settles first wins — the other paths become no-ops
    // (the list entry may already be gone, e.g. clearPendingWebhooks/pushTestWebhook
    // remove it themselves before calling resolve/reject; `indexOf` just won't find it).
    function finish(settle: () => void) {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      const idx = list.indexOf(pending);
      if (idx !== -1) list.splice(idx, 1);
      context?.signal?.removeEventListener('abort', onAbort);
      settle();
    }

    function onAbort() {
      // RN-08: a whole-workflow run races multiple triggers — a different one
      // already fired, so this wait no longer matters.
      finish(() => reject(new Error('Cancelled: another trigger in this test run already fired')));
    }

    const timer = setTimeout(() => {
      finish(() =>
        reject(
          new Error(
            `Timeout waiting for incoming webhook request on "${normalizedPath}" after ${timeoutMs / 1000}s. Send an HTTP request to the test URL and click Test again.`
          )
        )
      );
    }, timeoutMs);

    const pending: PendingWebhook = {
      path: normalizedPath,
      timer,
      resolve: (incoming) => {
        finish(() => resolve({ value: formatWebhookOutput(incoming?.body, incoming?.headers, incoming?.query), activeOutput: 'main' }));
      },
      reject: (err) => finish(() => reject(err)),
    };

    context?.signal?.addEventListener('abort', onAbort);
    list.push(pending);
  });
};
