import type { PluginModule, PluginExecutionContext } from '@runflux/plugin-system/types';

export const manifest: PluginModule['manifest'] = {
  id: 'trigger-webhook',
  name: 'Webhook Trigger',
  category: 'trigger',
  version: '1.0.0',
  parameters: [
    {
      name: 'path',
      label: 'Webhook Path',
      type: 'string',
      required: true,
      default: '/webhook',
    },
    {
      name: 'httpMethod',
      label: 'HTTP Method',
      type: 'string',
      required: true,
      default: 'POST',
    },
    {
      name: 'auth',
      label: 'Authentication Mode',
      type: 'string',
      required: false,
      default: 'none',
    },
    {
      name: 'secretEnvVar',
      label: 'Secret Environment Variable Name',
      type: 'string',
      required: false,
      default: 'WEBHOOK_SECRET',
    },
    {
      name: 'sampleBody',
      label: 'Sample Simulation Body (Fallback)',
      type: 'json',
      required: false,
      default: { message: 'Sample webhook payload' },
    },
    {
      name: 'sampleHeaders',
      label: 'Sample Headers',
      type: 'json',
      required: false,
      default: { 'content-type': 'application/json' },
    },
    {
      name: 'sampleQuery',
      label: 'Sample Query Params',
      type: 'json',
      required: false,
      default: {},
    },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['main'],
};

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => {
    const path = (nodeConfig.path as string) || '/webhook';
    const method = ((nodeConfig.httpMethod as string) || 'POST').toUpperCase();
    const auth = (nodeConfig.auth as string) || 'none';
    const secretEnvVar = (nodeConfig.secretEnvVar as string) || 'WEBHOOK_SECRET';

    return {
      files: [
        {
          path: 'trigger-webhook.ts',
          content: `// Generated by RunFlux for plugin "trigger-webhook"
export const WEBHOOK_PATH = ${JSON.stringify(path)};
export const WEBHOOK_METHOD = ${JSON.stringify(method)};
export const WEBHOOK_AUTH = ${JSON.stringify(auth)};
export const WEBHOOK_SECRET_ENV = ${JSON.stringify(secretEnvVar)};

export function run(input: any) {
  if (input && typeof input === 'object' && ('body' in input || 'headers' in input || 'query' in input)) {
    return input;
  }
  return {
    body: input ?? {},
    headers: {},
    query: {},
    path: WEBHOOK_PATH,
    method: WEBHOOK_METHOD,
    receivedAt: new Date().toISOString(),
  };
}
`,
        },
      ],
      infra: [],
    };
  },
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
};

interface PendingWebhook {
  path: string;
  resolve: (data: any) => void;
  reject: (err: any) => void;
  timer: any;
}

const pendingWebhooks: PendingWebhook[] = [];

/**
 * Pushes an incoming test webhook event from the dev server or project server
 * to any node currently awaiting an event in the canvas editor.
 */
export function pushTestWebhook(targetPath: string, payload: any): boolean {
  const normalizedPath = targetPath.startsWith('/') ? targetPath : `/${targetPath}`;
  const idx = pendingWebhooks.findIndex(
    (p) => p.path === normalizedPath || p.path === '*' || p.path.endsWith(normalizedPath) || normalizedPath.endsWith(p.path)
  );

  if (idx !== -1) {
    const pending = pendingWebhooks.splice(idx, 1)[0];
    clearTimeout(pending.timer);
    pending.resolve(payload);
    return true;
  }

  // If only one node is waiting on any path, resolve it
  if (pendingWebhooks.length === 1) {
    const pending = pendingWebhooks.splice(0, 1)[0];
    clearTimeout(pending.timer);
    pending.resolve(payload);
    return true;
  }

  return false;
}

/**
 * Clears any pending webhook listeners.
 */
export function clearPendingWebhooks(): void {
  while (pendingWebhooks.length > 0) {
    const p = pendingWebhooks.pop();
    if (p) {
      clearTimeout(p.timer);
      p.reject(new Error('Webhook listener cancelled'));
    }
  }
}

export const execute: PluginModule['execute'] = async (params, input, _context?: PluginExecutionContext) => {
  const reqInput = input && typeof input === 'object' ? (input as Record<string, unknown>) : null;

  // 1. If payload was already provided (e.g. from upstream caller or direct invocation):
  if (reqInput && ('body' in reqInput || 'headers' in reqInput || 'query' in reqInput)) {
    return {
      body: reqInput.body ?? {},
      headers: reqInput.headers ?? {},
      query: reqInput.query ?? {},
      method: (params.httpMethod as string) || 'POST',
      path: (params.path as string) || '/webhook',
      receivedAt: new Date().toISOString(),
    };
  }

  // 2. If running under automated unit tests without explicit waiting mode, return sample simulation body:
  if (process.env.NODE_ENV === 'test' && !process.env.RUNFLUX_WAIT_WEBHOOK_TEST) {
    const body = params.sampleBody ?? { message: 'Sample webhook payload' };
    const headers = params.sampleHeaders ?? { 'content-type': 'application/json' };
    const query = params.sampleQuery ?? {};

    return {
      body,
      headers,
      query,
      method: (params.httpMethod as string) || 'POST',
      path: (params.path as string) || '/webhook',
      receivedAt: new Date().toISOString(),
    };
  }

  // 3. User interactive test in canvas: wait for an actual HTTP request to arrive!
  const path = ((params.path as string) || '/webhook').trim();
  const normalizedPath = path.startsWith('/') ? path : `/${path}`;
  const timeoutMs = 60000; // 60s timeout

  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      const idx = pendingWebhooks.findIndex((p) => p.timer === timer);
      if (idx !== -1) pendingWebhooks.splice(idx, 1);
      reject(
        new Error(
          `Timeout waiting for incoming webhook request on "${normalizedPath}" after ${timeoutMs / 1000}s. Send an HTTP request to the test URL and click Test again.`
        )
      );
    }, timeoutMs);

    pendingWebhooks.push({
      path: normalizedPath,
      timer,
      resolve: (incoming) => {
        resolve({
          body: incoming?.body ?? {},
          headers: incoming?.headers ?? {},
          query: incoming?.query ?? {},
          method: incoming?.method ?? (params.httpMethod as string) ?? 'POST',
          path: normalizedPath,
          receivedAt: new Date().toISOString(),
        });
      },
      reject,
    });
  });
};
