export const manifest = {
    id: 'trigger-webhook',
    name: 'Webhook Trigger',
    category: 'trigger',
    version: '1.0.0',
    description: 'Listens for incoming HTTP requests and triggers synchronous workflow execution.',
    parameters: [
        {
            name: 'path',
            label: 'Webhook Path',
            type: 'string',
            required: true,
            default: '/webhook',
            description: 'URL path to listen on (must start with /).',
        },
        {
            name: 'httpMethod',
            label: 'HTTP Method',
            type: 'select',
            required: true,
            default: 'POST',
            options: [
                { label: 'POST', value: 'POST' },
                { label: 'GET', value: 'GET' },
                { label: 'PUT', value: 'PUT' },
                { label: 'DELETE', value: 'DELETE' },
                { label: 'ANY', value: 'ANY' },
            ],
        },
        {
            name: 'auth',
            label: 'Authentication Mode',
            type: 'select',
            required: false,
            default: 'none',
            options: [
                { label: 'None (Public Webhook)', value: 'none' },
                { label: 'Header Secret (X-Webhook-Secret)', value: 'secret' },
            ],
        },
        {
            name: 'secretEnvVar',
            label: 'Secret Environment Variable Name',
            type: 'string',
            required: false,
            default: 'WEBHOOK_SECRET',
            description: 'Environment variable name holding the expected secret token.',
        },
        {
            name: 'sampleBody',
            label: 'Sample Simulation Body (Canvas Testing)',
            type: 'json',
            required: false,
            default: { message: 'Sample webhook payload' },
        },
        {
            name: 'sampleHeaders',
            label: 'Sample Headers',
            type: 'json',
            required: false,
            default: { 'content-type': 'application/json' },
        },
        {
            name: 'sampleQuery',
            label: 'Sample Query Params',
            type: 'json',
            required: false,
            default: {},
        },
    ],
    supportedPlatforms: ['local', 'aws'],
    outputs: ['main'],
};
export const generators = {
    local: (nodeConfig) => {
        const path = nodeConfig.path || '/webhook';
        const method = (nodeConfig.httpMethod || 'POST').toUpperCase();
        const auth = nodeConfig.auth || 'none';
        const secretEnvVar = nodeConfig.secretEnvVar || 'WEBHOOK_SECRET';
        return {
            files: [
                {
                    path: 'trigger-webhook.ts',
                    content: `// Generated by RunFlux for plugin "trigger-webhook"
export const WEBHOOK_PATH = ${JSON.stringify(path)};
export const WEBHOOK_METHOD = ${JSON.stringify(method)};
export const WEBHOOK_AUTH = ${JSON.stringify(auth)};
export const WEBHOOK_SECRET_ENV = ${JSON.stringify(secretEnvVar)};

export function run(input: any) {
  if (input && typeof input === 'object' && ('body' in input || 'headers' in input || 'query' in input)) {
    return input;
  }
  return {
    body: input ?? {},
    headers: {},
    query: {},
    path: WEBHOOK_PATH,
    method: WEBHOOK_METHOD,
    receivedAt: new Date().toISOString(),
  };
}
`,
                },
            ],
            infra: [],
        };
    },
    aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
};
export const execute = (params, input) => {
    const reqInput = input && typeof input === 'object' ? input : null;
    const body = reqInput?.body ?? params.sampleBody ?? { message: 'Sample webhook payload' };
    const headers = reqInput?.headers ?? params.sampleHeaders ?? { 'content-type': 'application/json' };
    const query = reqInput?.query ?? params.sampleQuery ?? {};
    return {
        body,
        headers,
        query,
        method: params.httpMethod || 'POST',
        path: params.path || '/webhook',
        receivedAt: new Date().toISOString(),
    };
};
