export const manifest = {
    id: 'trigger-cron',
    name: 'Cron Trigger',
    category: 'trigger',
    version: '1.0.0',
    description: 'Schedules recurring workflow execution on a time-based schedule or interval.',
    parameters: [
        {
            name: 'preset',
            label: 'Schedule Preset',
            type: 'select',
            required: false,
            default: 'every15Minutes',
            options: [
                { label: 'Every Minute (* * * * *)', value: 'everyMinute' },
                { label: 'Every 5 Minutes (*/5 * * * *)', value: 'every5Minutes' },
                { label: 'Every 15 Minutes (*/15 * * * *)', value: 'every15Minutes' },
                { label: 'Hourly (0 * * * *)', value: 'everyHour' },
                { label: 'Daily at Midnight (0 0 * * *)', value: 'dailyMidnight' },
                { label: 'Custom Expression', value: 'custom' },
            ],
        },
        {
            name: 'expression',
            label: 'Cron Expression',
            type: 'string',
            required: true,
            default: '*/15 * * * *',
            description: 'Standard 5-part cron expression (minute hour day-of-month month day-of-week).',
        },
        {
            name: 'timezone',
            label: 'Timezone',
            type: 'string',
            required: false,
            default: 'UTC',
            description: 'IANA timezone for evaluation (e.g. UTC, America/Sao_Paulo, Europe/London).',
        },
    ],
    supportedPlatforms: ['local', 'aws'],
    outputs: ['main'],
};
export const generators = {
    local: (nodeConfig) => {
        const expression = nodeConfig.expression || '*/15 * * * *';
        const timezone = nodeConfig.timezone || 'UTC';
        return {
            files: [
                {
                    path: 'trigger-cron.ts',
                    content: `// Generated by RunFlux for plugin "trigger-cron"
export const CRON_EXPRESSION = ${JSON.stringify(expression)};
export const CRON_TIMEZONE = ${JSON.stringify(timezone)};

export function run(input: any) {
  const base = input && typeof input === 'object' ? input : {};
  return {
    ...base,
    triggeredAt: new Date().toISOString(),
    cronExpression: CRON_EXPRESSION,
    timezone: CRON_TIMEZONE,
  };
}
`,
                },
            ],
            infra: [],
        };
    },
    aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
};
export const execute = (params, input) => {
    const base = input && typeof input === 'object' ? input : {};
    const expression = params.expression || '*/15 * * * *';
    const timezone = params.timezone || 'UTC';
    return {
        ...base,
        triggeredAt: new Date().toISOString(),
        cronExpression: expression,
        timezone,
    };
};
