import type { PluginModule, PluginExecutionContext } from '@runflux/plugin-system/types';

export const manifest: PluginModule['manifest'] = {
  id: 'trigger-cron',
  name: 'Cron Trigger',
  category: 'trigger',
  version: '1.0.0',
  parameters: [
    {
      name: 'preset',
      label: 'Schedule Preset',
      type: 'string',
      required: false,
      default: 'every15Minutes',
    },
    {
      name: 'expression',
      label: 'Cron Expression',
      type: 'string',
      required: true,
      default: '*/15 * * * *',
    },
    {
      name: 'timezone',
      label: 'Timezone',
      type: 'string',
      required: false,
      default: 'UTC',
    },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['main'],
};

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => {
    const expression = (nodeConfig.expression as string) || '*/15 * * * *';
    const timezone = (nodeConfig.timezone as string) || 'UTC';
    return {
      files: [
        {
          path: 'trigger-cron.ts',
          content: `// Generated by RunFlux for plugin "trigger-cron"
export const CRON_EXPRESSION = ${JSON.stringify(expression)};
export const CRON_TIMEZONE = ${JSON.stringify(timezone)};

export function run(input: any) {
  const base = input && typeof input === 'object' ? input : {};
  return { value: {
    ...base,
    triggeredAt: new Date().toISOString(),
    cronExpression: CRON_EXPRESSION,
    timezone: CRON_TIMEZONE,
  }, activeOutput: 'main' };
}
`,
        },
      ],
      infra: [],
    };
  },
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
};

export const execute: PluginModule['execute'] = (params, input, _context?: PluginExecutionContext) => {
  const base = input && typeof input === 'object' ? (input as Record<string, unknown>) : {};
  const expression = (params.expression as string) || '*/15 * * * *';
  const timezone = (params.timezone as string) || 'UTC';

  return { value: {
    ...base,
    triggeredAt: new Date().toISOString(),
    cronExpression: expression,
    timezone,
  }, activeOutput: 'main' };
};
