import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * Minimal example plugin, used as the fixture for onboarding.md's manual
 * walkthrough. A "manual" trigger: the developer fires it on demand from the
 * editor (see validation-runtime spec) instead of waiting for a real webhook/cron.
 *
 * Ships as its own package (@runflux/plugin-trigger-manual-example), consuming
 * the core via the published package name rather than a relative path into
 * @runflux/plugin-system's internals — this is the pattern every real plugin
 * (in its own repo/package) is expected to follow.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'trigger-manual-example',
  name: 'Manual Trigger (Example)',
  category: 'trigger',
  version: '1.0.0',
  parameters: [
    { name: 'label', label: 'Label', type: 'string', required: false, default: 'Manual run' },
  ],
  supportedPlatforms: ['local'],
};

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => ({
    files: [
      {
        path: 'trigger-manual-example.ts',
        content: `// Generated by RunFlux for plugin "trigger-manual-example"\nexport const label = ${JSON.stringify(nodeConfig.label ?? 'Manual run')};\n`,
      },
    ],
    infra: [],
  }),
};

/**
 * Runtime executor (003-validation-runtime, D-05): fires the trigger on
 * demand during validation, distinct from `generators.local` above (which
 * only produces compile-time file/infra text, never runs anything).
 */
export const execute: PluginModule['execute'] = (params) => ({
  label: (params.label as string | undefined) ?? 'Manual run',
  triggeredAt: new Date().toISOString(),
});
