import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * Minimal example plugin, used as the fixture for onboarding.md's manual
 * walkthrough. A "manual" trigger: the developer fires it on demand from the
 * editor (see validation-runtime spec) instead of waiting for a real webhook/cron.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'trigger-manual-example',
  name: 'Manual Trigger (Example)',
  category: 'trigger',
  version: '1.0.0',
  parameters: [
    { name: 'label', label: 'Label', type: 'string', required: false, default: 'Manual run' },
  ],
  supportedPlatforms: ['local'],
};

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => ({
    files: [
      {
        path: 'trigger-manual-example.ts',
        content: `// Generated by RunFlux for plugin "trigger-manual-example"
export const label = ${JSON.stringify(nodeConfig.label ?? 'Manual run')};

export function run(input: any) {
  const base = input && typeof input === 'object' ? input : {};
  return {
    ...base,
    trigger: {
      label,
      triggeredAt: new Date().toISOString(),
    },
  };
}
`,
      },
    ],
    infra: [],
  }),
};

export const execute: PluginModule['execute'] = (params, input) => {
  const base = input && typeof input === 'object' ? (input as Record<string, unknown>) : {};
  return {
    ...base,
    label: (params.label as string | undefined) ?? 'Manual run',
    triggeredAt: new Date().toISOString(),
  };
};
