import { queryDatabase } from './runtime.js';
import { extractContext } from '@runflux/plugin-system/context-helpers';
import { bundleStandalone } from '@runflux/plugin-system/standalone';
import { STANDALONE_EXPRESSION_EVALUATOR_CODE } from '@runflux/plugin-system/snippets';
export { closeDatabasePools } from './runtime.js';
import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * Database Query Node (012-database-query-plugin): executes parameterized
 * SQL queries against PostgreSQL with connection pooling.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'database-query',
  name: 'Database Query',
  category: 'action',
  version: '1.0.0',
  parameters: [
    {
      name: 'databaseType',
      label: 'Database Engine',
      type: 'string',
      required: true,
      default: 'postgres',
    },
    {
      name: 'connectionEnvVar',
      label: 'Connection Env Var',
      type: 'string',
      required: true,
      default: 'DATABASE_URL',
    },
    {
      name: 'query',
      label: 'SQL Query',
      expressions: false,
      type: 'string',
      required: true,
      default: 'SELECT * FROM users LIMIT 10;',
    },
    { name: 'queryParams', label: 'Query Parameters ($1, $2, ...)', type: 'json', required: false, default: [] },
    {
      name: 'outputMode',
      label: 'Output Mode',
      type: 'string',
      required: false,
      default: 'all',
    },
  ],
  supportedPlatforms: ['local', 'aws'],
};

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    if (nodeConfig.databaseType && nodeConfig.databaseType !== 'postgres') {
      throw new Error(`database-query: unsupported database engine "${nodeConfig.databaseType}"`);
    }
    return {
      files: [{ path: 'database-query.ts', content: `// Generated by RunFlux for plugin "database-query"
${bundleStandalone('@runflux/plugin-database-query/runtime', ['queryDatabase', 'closeDatabasePools'], '__runfluxDatabase', ['pg'])}
${STANDALONE_EXPRESSION_EVALUATOR_CODE}
const CONFIG = ${JSON.stringify(nodeConfig)};
export async function run(input, context) {
  const env = context?.$env ?? process.env;
  const params = { ...resolveValue({ ...CONFIG, query: undefined }, input, context?.$node, env), query: CONFIG.query };
  return queryDatabase(params, env);
}
export { closeDatabasePools };
` }],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = async (params, input, context) => {
  if (context?.mode === 'production') return queryDatabase(params, extractContext(context).$env);
  const query = (params.query as string | undefined)?.trim() || 'SELECT 1;';
  const outputMode = (params.outputMode as string | undefined) || 'all';

  // In testing/sandbox environments, return simulated records based on the input
  const mockRecord = {
    id: (input as any)?.id ?? 1,
    query_executed: query,
    success: true,
    ...(typeof input === 'object' && input !== null ? input : { input }),
  };

  if (outputMode === 'first') {
    return mockRecord;
  }
  return [mockRecord];
};
