import type { PluginModule } from '@runflux/plugin-system/types';
import { FIELDS_ROW_SCHEMA, composeFields, type FieldConfig } from '@runflux/plugin-system/fields-row-schema';
import { STANDALONE_EXPRESSION_EVALUATOR_CODE } from '@runflux/plugin-system/snippets';

/**
 * Set (004-core-nodes-catalog, RF-11): composes an output object from
 * manually defined fields (literal or `{{ }}` expression values), optionally
 * keeping the rest of the input object. Modeled after n8n's "Edit Fields
 * (Set)" node (packages/nodes-base/nodes/Set/v2/SetV2.node.ts), manual-mapping
 * mode only — the JSON mode is out of scope for v1.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'set',
  name: 'Edit Fields (Set)',
  category: 'action',
  version: '1.0.0',
  parameters: [
    { name: 'fields', label: 'Fields', type: 'json', required: true, default: [], rowSchema: FIELDS_ROW_SCHEMA },
    { name: 'includeOtherFields', label: 'Include other input fields', type: 'boolean', required: false, default: false },
  ],
  supportedPlatforms: ['local', 'aws'],
};

function compose(fields: FieldConfig[], includeOtherFields: boolean, input: unknown): Record<string, unknown> {
  const base: Record<string, unknown> =
    includeOtherFields && input !== null && typeof input === 'object' ? { ...(input as Record<string, unknown>) } : {};
  return { ...base, ...composeFields(fields) };
}

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const fields = JSON.stringify(Array.isArray(nodeConfig.fields) ? nodeConfig.fields : []);
    const includeOtherFields = JSON.stringify(Boolean(nodeConfig.includeOtherFields));
    return {
      files: [
        {
          path: 'set.ts',
          content: `// Generated by RunFlux for plugin "set"
const FIELDS = ${fields};
const INCLUDE_OTHER_FIELDS = ${includeOtherFields};

${STANDALONE_EXPRESSION_EVALUATOR_CODE}

function normalizeFieldValue(field, value) {
  if (field.type === 'null') return null;
  if (field.type === 'array') {
    if (Array.isArray(value)) return value;
    throw new Error('Field "' + field.name + '" must be an array');
  }
  if (field.type === 'object') {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) return value;
    throw new Error('Field "' + field.name + '" must be an object');
  }
  if (field.type === 'number') {
    const numberValue = typeof value === 'number' ? value : typeof value === 'string' && value.trim() !== '' ? Number(value) : Number.NaN;
    if (Number.isFinite(numberValue)) return numberValue;
    throw new Error('Field "' + field.name + '" must be a number');
  }
  if (field.type === 'boolean') {
    if (typeof value === 'boolean') return value;
    if (value === 'true') return true;
    if (value === 'false') return false;
    throw new Error('Field "' + field.name + '" must be a boolean');
  }
  if (field.type === 'string' && typeof value !== 'string') {
    if (value === null || value === undefined) return '';
    return typeof value === 'object' ? JSON.stringify(value) : String(value);
  }
  return value;
}

export function run($json, context) {
  const $node = context?.$node || {};
  const $env = context?.$env || (typeof process !== 'undefined' ? process.env : {});
  const base = INCLUDE_OTHER_FIELDS && $json !== null && typeof $json === 'object' ? { ...$json } : {};
  for (const field of FIELDS) {
    if (field && typeof field.name === 'string') {
      base[field.name] = normalizeFieldValue(field, resolveValue(field.value, $json, $node, $env));
    }
  }
  return base;
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const fields = Array.isArray(params.fields) ? (params.fields as FieldConfig[]) : [];
  const includeOtherFields = Boolean(params.includeOtherFields);
  return compose(fields, includeOtherFields, input);
};
