import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * Set (004-core-nodes-catalog, RF-11): composes an output object from
 * manually defined fields (literal or `{{ }}` expression values), optionally
 * keeping the rest of the input object. Modeled after n8n's "Edit Fields
 * (Set)" node (packages/nodes-base/nodes/Set/v2/SetV2.node.ts), manual-mapping
 * mode only — the JSON mode is out of scope for v1.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'set',
  name: 'Edit Fields (Set)',
  category: 'action',
  version: '1.0.0',
  parameters: [
    { name: 'fields', label: 'Fields', type: 'json', required: true, default: [] },
    { name: 'includeOtherFields', label: 'Include other input fields', type: 'boolean', required: false, default: false },
  ],
  supportedPlatforms: ['local'],
};

interface FieldConfig {
  name: string;
  value: unknown;
}

function compose(fields: FieldConfig[], includeOtherFields: boolean, input: unknown): Record<string, unknown> {
  const base: Record<string, unknown> =
    includeOtherFields && input !== null && typeof input === 'object' ? { ...(input as Record<string, unknown>) } : {};
  for (const field of fields) {
    if (field && typeof field.name === 'string') {
      base[field.name] = field.value;
    }
  }
  return base;
}

export const generators: PluginModule['generators'] = {
  local: (nodeConfig) => {
    const fields = JSON.stringify(Array.isArray(nodeConfig.fields) ? nodeConfig.fields : []);
    const includeOtherFields = JSON.stringify(Boolean(nodeConfig.includeOtherFields));
    return {
      files: [
        {
          path: 'set.ts',
          content: `// Generated by RunFlux for plugin "set"
const FIELDS = ${fields};
const INCLUDE_OTHER_FIELDS = ${includeOtherFields};

// Standalone {{ }} evaluator copy (004-core-nodes-catalog, D-08) — this file
// never runs through @runflux/validation-runtime, so it resolves its own expressions.
function evaluateExpression(expr, $json) {
  return new Function('$json', 'return (' + expr + ')')($json);
}
function resolveValue(raw, $json) {
  if (typeof raw !== 'string') return raw;
  const trimmed = raw.trim();
  const whole = /^{{([\\s\\S]*)}}\$/.exec(trimmed);
  if (whole) return evaluateExpression(whole[1].trim(), $json);
  return raw.replace(/{{([\\s\\S]*?)}}/g, (_m, expr) => String(evaluateExpression(expr.trim(), $json)));
}

export function run($json) {
  const base = INCLUDE_OTHER_FIELDS && $json !== null && typeof $json === 'object' ? { ...$json } : {};
  for (const field of FIELDS) {
    if (field && typeof field.name === 'string') {
      base[field.name] = resolveValue(field.value, $json);
    }
  }
  return base;
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const fields = Array.isArray(params.fields) ? (params.fields as FieldConfig[]) : [];
  const includeOtherFields = Boolean(params.includeOtherFields);
  return compose(fields, includeOtherFields, input);
};
