import type { PluginModule } from '@runflux/plugin-system/types';
import { RULE_ROW_SCHEMA } from '@runflux/plugin-system/condition-row-schema';

/**
 * Switch (004-core-nodes-catalog, RF-02): evaluates a list of rules in
 * order, routing to the first one that matches (or "fallback" if enabled and
 * none match). Modeled after n8n's Switch node's "rules" mode
 * (packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts) — the "expression"
 * mode (output count computed by an expression) is out of scope for v1.
 *
 * `PluginManifest.outputs` is authored once, statically, at plugin-definition
 * time (004-core-nodes-catalog, D-03) — it cannot vary per node instance. A
 * fixed set of positional rule slots (RULE_OUTPUTS) plus "fallback" is the v1
 * compromise: a node's Nth configured rule activates RULE_OUTPUTS[N] when it
 * matches (rules beyond RULE_OUTPUTS.length are never reachable).
 */
const RULE_OUTPUTS = ['output1', 'output2', 'output3', 'output4', 'output5'];

export const manifest: PluginModule['manifest'] = {
  id: 'condition-switch',
  name: 'Switch',
  category: 'control-flow',
  version: '1.0.0',
  parameters: [
    { name: 'rules', label: 'Rules (ordered, first match wins)', type: 'json', required: true, default: [], rowSchema: RULE_ROW_SCHEMA },
    { name: 'fallbackEnabled', label: 'Enable fallback output', type: 'boolean', required: false, default: false },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: [...RULE_OUTPUTS, 'fallback'],
};

interface ConditionRule {
  leftValue: unknown;
  operator: 'equals' | 'notEquals' | 'contains' | 'greaterThan' | 'lessThan' | 'isEmpty';
  rightValue?: unknown;
}

interface SwitchRule {
  combinator?: string;
  conditions?: ConditionRule[];
}

function compare(left: unknown, operator: ConditionRule['operator'], right: unknown): boolean {
  switch (operator) {
    case 'equals':
      return left === right || String(left) === String(right);
    case 'notEquals':
      return !(left === right || String(left) === String(right));
    case 'contains':
      return String(left).includes(String(right));
    case 'greaterThan':
      return Number(left) > Number(right);
    case 'lessThan':
      return Number(left) < Number(right);
    case 'isEmpty':
      return left === undefined || left === null || left === '' || (Array.isArray(left) && left.length === 0);
    default:
      return false;
  }
}

function combine(results: boolean[], combinator: string): boolean {
  if (results.length === 0) return true;
  return combinator === 'or' ? results.some(Boolean) : results.every(Boolean);
}

function matchRule(rule: SwitchRule): boolean {
  const conditions = Array.isArray(rule.conditions) ? rule.conditions : [];
  const results = conditions.map((c) => compare(c.leftValue, c.operator, c.rightValue));
  return combine(results, rule.combinator ?? 'and');
}

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const rules = JSON.stringify(Array.isArray(nodeConfig.rules) ? nodeConfig.rules : []);
    const fallbackEnabled = JSON.stringify(Boolean(nodeConfig.fallbackEnabled));
    const ruleOutputs = JSON.stringify(RULE_OUTPUTS);
    return {
      files: [
        {
          path: 'condition-switch.ts',
          content: `// Generated by RunFlux for plugin "condition-switch"
const RULES = ${rules};
const FALLBACK_ENABLED = ${fallbackEnabled};
const RULE_OUTPUTS = ${ruleOutputs};

// Standalone {{ }} evaluator copy (004-core-nodes-catalog, D-08, 009-expression-global-context)
function evaluateExpression(expr, $json, $node, $env) {
  const safeNode = new Proxy($node || {}, {
    get(target, prop) {
      if (typeof prop === 'string') {
        if (prop in target) return target[prop];
        return { json: undefined };
      }
      return undefined;
    }
  });
  const safeEnv = $env || (typeof process !== 'undefined' ? process.env : {});
  return new Function('$json', '$node', '$env', 'return (' + expr + ')')($json, safeNode, safeEnv);
}
function resolveValue(raw, $json, $node, $env) {
  if (typeof raw !== 'string') return raw;
  const trimmed = raw.trim();
  const whole = /^{{([\\s\\S]*)}}\$/.exec(trimmed);
  if (whole) return evaluateExpression(whole[1].trim(), $json, $node, $env);
  return raw.replace(/{{([\\s\\S]*?)}}/g, (_m, expr) => String(evaluateExpression(expr.trim(), $json, $node, $env)));
}
function compare(left, operator, right) {
  switch (operator) {
    case 'equals': return left === right || String(left) === String(right);
    case 'notEquals': return !(left === right || String(left) === String(right));
    case 'contains': return String(left).includes(String(right));
    case 'greaterThan': return Number(left) > Number(right);
    case 'lessThan': return Number(left) < Number(right);
    case 'isEmpty': return left === undefined || left === null || left === '' || (Array.isArray(left) && left.length === 0);
    default: return false;
  }
}
function combine(results, combinator) {
  if (results.length === 0) return true;
  return combinator === 'or' ? results.some(Boolean) : results.every(Boolean);
}
function matchRule(rule, $json, $node, $env) {
  const conditions = Array.isArray(rule && rule.conditions) ? rule.conditions : [];
  const results = conditions.map((c) => compare(resolveValue(c.leftValue, $json, $node, $env), c.operator, resolveValue(c.rightValue, $json, $node, $env)));
  return combine(results, (rule && rule.combinator) || 'and');
}

export function run($json, context) {
  const $node = context?.$node || {};
  const $env = context?.$env || (typeof process !== 'undefined' ? process.env : {});
  for (let i = 0; i < RULES.length && i < RULE_OUTPUTS.length; i++) {
    if (matchRule(RULES[i], $json, $node, $env)) {
      return { value: $json, activeOutput: RULE_OUTPUTS[i] };
    }
  }
  if (FALLBACK_ENABLED) return { value: $json, activeOutput: 'fallback' };
  return { value: $json, activeOutput: null };
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const rules = Array.isArray(params.rules) ? (params.rules as SwitchRule[]) : [];
  const fallbackEnabled = Boolean(params.fallbackEnabled);

  for (let i = 0; i < rules.length && i < RULE_OUTPUTS.length; i++) {
    if (matchRule(rules[i])) {
      return { value: input, activeOutput: RULE_OUTPUTS[i] };
    }
  }
  if (fallbackEnabled) {
    return { value: input, activeOutput: 'fallback' };
  }
  return { value: input, activeOutput: null };
};
