import type { PluginModule } from '@runflux/plugin-system/types';
import { RULE_ROW_SCHEMA } from '@runflux/plugin-system/condition-row-schema';
import { matchRule, type ConditionRule } from '@runflux/plugin-system/operators';
import { STANDALONE_OPERATOR_CODE, STANDALONE_EXPRESSION_EVALUATOR_CODE } from '@runflux/plugin-system/snippets';

/**
 * Switch (004-core-nodes-catalog, RF-02): evaluates a list of rules in
 * order, routing to the first one that matches (or "fallback" if enabled and
 * none match). Modeled after n8n's Switch node's "rules" mode.
 */
const RULE_OUTPUTS = ['output1', 'output2', 'output3', 'output4', 'output5'];

export const manifest: PluginModule['manifest'] = {
  id: 'condition-switch',
  name: 'Switch',
  category: 'control-flow',
  version: '1.0.0',
  parameters: [
    { name: 'rules', label: 'Rules (ordered, first match wins)', type: 'json', required: true, default: [], rowSchema: RULE_ROW_SCHEMA },
    { name: 'fallbackEnabled', label: 'Enable fallback output', type: 'boolean', required: false, default: false },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: [...RULE_OUTPUTS, 'fallback'],
};

export interface SwitchRule {
  combinator?: string;
  conditions?: ConditionRule[];
}

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const rules = JSON.stringify(Array.isArray(nodeConfig.rules) ? nodeConfig.rules : []);
    const fallbackEnabled = JSON.stringify(Boolean(nodeConfig.fallbackEnabled));
    const ruleOutputs = JSON.stringify(RULE_OUTPUTS);
    return {
      files: [
        {
          path: 'condition-switch.ts',
          content: `// Generated by RunFlux for plugin "condition-switch"
const RULES = ${rules};
const FALLBACK_ENABLED = ${fallbackEnabled};
const RULE_OUTPUTS = ${ruleOutputs};

${STANDALONE_EXPRESSION_EVALUATOR_CODE}
${STANDALONE_OPERATOR_CODE}

function matchSwitchRule(rule, $json, $node, $env) {
  const conditions = Array.isArray(rule && rule.conditions) ? rule.conditions : [];
  const results = conditions.map((c) => compare(resolveValue(c.leftValue, $json, $node, $env), c.operator, resolveValue(c.rightValue, $json, $node, $env)));
  return combine(results, (rule && rule.combinator) || 'and');
}

export function run($json, context) {
  const $node = context?.$node || {};
  const $env = context?.$env || (typeof process !== 'undefined' ? process.env : {});
  for (let i = 0; i < RULES.length && i < RULE_OUTPUTS.length; i++) {
    if (matchSwitchRule(RULES[i], $json, $node, $env)) {
      return { value: $json, activeOutput: RULE_OUTPUTS[i] };
    }
  }
  if (FALLBACK_ENABLED) return { value: $json, activeOutput: 'fallback' };
  return { value: $json, activeOutput: null };
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const rules = Array.isArray(params.rules) ? (params.rules as SwitchRule[]) : [];
  const fallbackEnabled = Boolean(params.fallbackEnabled);

  for (let i = 0; i < rules.length && i < RULE_OUTPUTS.length; i++) {
    const rule = rules[i];
    if (matchRule(rule?.conditions, rule?.combinator ?? 'and')) {
      return { value: input, activeOutput: RULE_OUTPUTS[i] };
    }
  }
  if (fallbackEnabled) {
    return { value: input, activeOutput: 'fallback' };
  }
  return { value: input, activeOutput: null };
};
