import type { PluginModule } from '@runflux/plugin-system/types';
import { CONDITION_ROW_SCHEMA } from '@runflux/plugin-system/condition-row-schema';
import { matchRule, type ConditionRule } from '@runflux/plugin-system/operators';
import { STANDALONE_OPERATOR_CODE, STANDALONE_EXPRESSION_EVALUATOR_CODE } from '@runflux/plugin-system/snippets';

/**
 * Filter (004-core-nodes-catalog, RF-03): propagates the input unchanged
 * through its single output when its condition matches; otherwise activates
 * no output, silently halting the branch (RN-02) — same as n8n's Filter node.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'filter',
  name: 'Filter',
  category: 'control-flow',
  version: '1.0.0',
  parameters: [
    { name: 'combinator', label: 'Combinator (and/or)', type: 'string', required: false, default: 'and' },
    { name: 'conditions', label: 'Conditions', type: 'json', required: true, default: [], rowSchema: CONDITION_ROW_SCHEMA },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['main'],
};

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const conditions = JSON.stringify(Array.isArray(nodeConfig.conditions) ? nodeConfig.conditions : []);
    const combinator = JSON.stringify((nodeConfig.combinator as string | undefined) ?? 'and');
    return {
      files: [
        {
          path: 'filter.ts',
          content: `// Generated by RunFlux for plugin "filter"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

${STANDALONE_EXPRESSION_EVALUATOR_CODE}
${STANDALONE_OPERATOR_CODE}

export function run($json, context) {
  const $node = context?.$node || {};
  const $env = context?.$env || (typeof process !== 'undefined' ? process.env : {});
  const results = CONDITIONS.map((c) => compare(resolveValue(c.leftValue, $json, $node, $env), c.operator, resolveValue(c.rightValue, $json, $node, $env)));
  const matched = combine(results, COMBINATOR);
  return { value: $json, activeOutput: matched ? 'main' : null };
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const conditions = Array.isArray(params.conditions) ? (params.conditions as ConditionRule[]) : [];
  const combinator = (params.combinator as string | undefined) ?? 'and';
  const matched = matchRule(conditions, combinator);
  return { value: input, activeOutput: matched ? 'main' : null };
};
