import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * Filter (004-core-nodes-catalog, RF-03): propagates the input unchanged
 * through its single output when its condition matches; otherwise activates
 * no output, silently halting the branch (RN-02) — same as n8n's Filter node.
 * Declares `outputs: ['main']` (not the legacy absent form) specifically so
 * it can use the `{ value, activeOutput: null }` gate (D-03).
 */
export const manifest: PluginModule['manifest'] = {
  id: 'filter',
  name: 'Filter',
  category: 'control-flow',
  version: '1.0.0',
  parameters: [
    { name: 'combinator', label: 'Combinator (and/or)', type: 'string', required: false, default: 'and' },
    { name: 'conditions', label: 'Conditions', type: 'json', required: true, default: [] },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['main'],
};

interface ConditionRule {
  leftValue: unknown;
  operator: 'equals' | 'notEquals' | 'contains' | 'greaterThan' | 'lessThan' | 'isEmpty';
  rightValue?: unknown;
}

function compare(left: unknown, operator: ConditionRule['operator'], right: unknown): boolean {
  switch (operator) {
    case 'equals':
      return left === right || String(left) === String(right);
    case 'notEquals':
      return !(left === right || String(left) === String(right));
    case 'contains':
      return String(left).includes(String(right));
    case 'greaterThan':
      return Number(left) > Number(right);
    case 'lessThan':
      return Number(left) < Number(right);
    case 'isEmpty':
      return left === undefined || left === null || left === '' || (Array.isArray(left) && left.length === 0);
    default:
      return false;
  }
}

function combine(results: boolean[], combinator: string): boolean {
  if (results.length === 0) return true;
  return combinator === 'or' ? results.some(Boolean) : results.every(Boolean);
}

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const conditions = JSON.stringify(Array.isArray(nodeConfig.conditions) ? nodeConfig.conditions : []);
    const combinator = JSON.stringify((nodeConfig.combinator as string | undefined) ?? 'and');
    return {
      files: [
        {
          path: 'filter.ts',
          content: `// Generated by RunFlux for plugin "filter"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

// Standalone {{ }} evaluator copy (004-core-nodes-catalog, D-08) — this file
// never runs through @runflux/validation-runtime, so it resolves its own expressions.
function evaluateExpression(expr, $json) {
  return new Function('$json', 'return (' + expr + ')')($json);
}
function resolveValue(raw, $json) {
  if (typeof raw !== 'string') return raw;
  const trimmed = raw.trim();
  const whole = /^{{([\\s\\S]*)}}\$/.exec(trimmed);
  if (whole) return evaluateExpression(whole[1].trim(), $json);
  return raw.replace(/{{([\\s\\S]*?)}}/g, (_m, expr) => String(evaluateExpression(expr.trim(), $json)));
}
function compare(left, operator, right) {
  switch (operator) {
    case 'equals': return left === right || String(left) === String(right);
    case 'notEquals': return !(left === right || String(left) === String(right));
    case 'contains': return String(left).includes(String(right));
    case 'greaterThan': return Number(left) > Number(right);
    case 'lessThan': return Number(left) < Number(right);
    case 'isEmpty': return left === undefined || left === null || left === '' || (Array.isArray(left) && left.length === 0);
    default: return false;
  }
}
function combine(results, combinator) {
  if (results.length === 0) return true;
  return combinator === 'or' ? results.some(Boolean) : results.every(Boolean);
}

export function run($json) {
  const results = CONDITIONS.map((c) => compare(resolveValue(c.leftValue, $json), c.operator, resolveValue(c.rightValue, $json)));
  const matched = combine(results, COMBINATOR);
  return { value: $json, activeOutput: matched ? 'main' : null };
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const conditions = Array.isArray(params.conditions) ? (params.conditions as ConditionRule[]) : [];
  const combinator = (params.combinator as string | undefined) ?? 'and';
  const results = conditions.map((c) => compare(c.leftValue, c.operator, c.rightValue));
  const matched = combine(results, combinator);
  return { value: input, activeOutput: matched ? 'main' : null };
};
