import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * HTTP Request (Output) (004-core-nodes-catalog, RF-04): fires a real HTTP
 * request via native `fetch`, no destination allowlist (RNF Segurança,
 * `requirements.md#6`, user-confirmed). See `interfaces/http-output.md` for
 * the full request/response/error contract.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'http-output',
  name: 'HTTP Request',
  category: 'output',
  version: '1.0.0',
  parameters: [
    { name: 'method', label: 'Method', type: 'string', required: true, default: 'GET' },
    { name: 'url', label: 'URL', type: 'string', required: true },
    { name: 'headers', label: 'Headers', type: 'json', required: false, default: {} },
    { name: 'body', label: 'Body', type: 'json', required: false, default: {} },
  ],
  supportedPlatforms: ['local', 'aws'],
};

async function callHttp(
  method: string,
  url: unknown,
  headers: unknown,
  body: unknown,
  fetchImpl: typeof fetch,
): Promise<{ status: number; headers: Record<string, string>; body: unknown }> {
  if (typeof url !== 'string' || url.trim() === '') {
    throw new Error('http-output: "url" is empty or invalid');
  }
  const upperMethod = method.toUpperCase();
  const requestHeaders: Record<string, string> = { ...(headers as Record<string, string> | undefined) };
  const init: RequestInit = { method: upperMethod, headers: requestHeaders };
  if (upperMethod !== 'GET' && upperMethod !== 'HEAD' && body !== undefined) {
    requestHeaders['Content-Type'] ??= 'application/json';
    init.body = JSON.stringify(body);
  }

  const response = await fetchImpl(url, init);
  const responseHeaders: Record<string, string> = {};
  response.headers.forEach((value, key) => {
    responseHeaders[key] = value;
  });
  const contentType = response.headers.get('content-type') ?? '';
  const rawBody = await response.text();
  let parsedBody: unknown = rawBody;
  if (contentType.includes('application/json')) {
    try {
      parsedBody = JSON.parse(rawBody);
    } catch {
      parsedBody = rawBody;
    }
  }

  if (!response.ok) {
    throw new Error(`http-output: request to ${url} failed with status ${response.status}: ${rawBody.slice(0, 200)}`);
  }

  return { status: response.status, headers: responseHeaders, body: parsedBody };
}

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const method = JSON.stringify((nodeConfig.method as string | undefined) ?? 'GET');
    const url = JSON.stringify(nodeConfig.url ?? '');
    const headers = JSON.stringify(nodeConfig.headers ?? {});
    const body = JSON.stringify(nodeConfig.body ?? {});
    return {
      files: [
        {
          path: 'http-output.ts',
          content: `// Generated by RunFlux for plugin "http-output"
const METHOD = ${method};
const URL_TEMPLATE = ${url};
const HEADERS_TEMPLATE = ${headers};
const BODY_TEMPLATE = ${body};

// Standalone {{ }} evaluator copy (004-core-nodes-catalog, D-08, 009-expression-global-context)
function evaluateExpression(expr, $json, $node, $env) {
  const safeNode = new Proxy($node || {}, {
    get(target, prop) {
      if (typeof prop === 'string') {
        if (prop in target) return target[prop];
        return { json: undefined };
      }
      return undefined;
    }
  });
  const safeEnv = $env || (typeof process !== 'undefined' ? process.env : {});
  return new Function('$json', '$node', '$env', 'return (' + expr + ')')($json, safeNode, safeEnv);
}
function resolveValue(raw, $json, $node, $env) {
  if (typeof raw !== 'string') {
    if (Array.isArray(raw)) return raw.map((v) => resolveValue(v, $json, $node, $env));
    if (raw !== null && typeof raw === 'object') {
      const out = {};
      for (const [k, v] of Object.entries(raw)) out[k] = resolveValue(v, $json, $node, $env);
      return out;
    }
    return raw;
  }
  const trimmed = raw.trim();
  const whole = /^{{([\\s\\S]*)}}\$/.exec(trimmed);
  if (whole) return evaluateExpression(whole[1].trim(), $json, $node, $env);
  return raw.replace(/{{([\\s\\S]*?)}}/g, (_m, expr) => String(evaluateExpression(expr.trim(), $json, $node, $env)));
}

export async function run($json, context) {
  const $node = context?.$node || {};
  const $env = context?.$env || (typeof process !== 'undefined' ? process.env : {});
  const url = resolveValue(URL_TEMPLATE, $json, $node, $env);
  if (typeof url !== 'string' || url.trim() === '') {
    throw new Error('http-output: "url" is empty or invalid');
  }
  const method = METHOD.toUpperCase();
  const headers = resolveValue(HEADERS_TEMPLATE, $json, $node, $env);
  const body = resolveValue(BODY_TEMPLATE, $json, $node, $env);
  const init = { method, headers };
  if (method !== 'GET' && method !== 'HEAD') {
    headers['Content-Type'] = headers['Content-Type'] || 'application/json';
    init.body = JSON.stringify(body);
  }
  const response = await fetch(url, init);
  const responseHeaders = {};
  response.headers.forEach((value, key) => { responseHeaders[key] = value; });
  const contentType = response.headers.get('content-type') || '';
  const rawBody = await response.text();
  let parsedBody = rawBody;
  if (contentType.includes('application/json')) {
    try { parsedBody = JSON.parse(rawBody); } catch { parsedBody = rawBody; }
  }
  if (!response.ok) {
    throw new Error('http-output: request to ' + url + ' failed with status ' + response.status + ': ' + rawBody.slice(0, 200));
  }
  return { status: response.status, headers: responseHeaders, body: parsedBody };
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = async (params) => {
  const method = (params.method as string | undefined) ?? 'GET';
  return callHttp(method, params.url, params.headers, params.body, fetch);
};
