import { bundleStandalone } from '@runflux/plugin-system/standalone';
export { executeWorkflowGraph } from '../runner-runtime.js';
export type { GraphConnection, GraphNode, WorkflowExecutionResult } from '../runner-runtime.js';

export function generateRunnerRuntime(): string {
  return bundleStandalone('@runflux/compiler/runner-runtime', ['executeWorkflowGraph'], '__runfluxGraph') + '\nexport { executeWorkflowGraph };\n';
}

export function buildRunnerCode(imports: string[], graphNodesCode: string, connectionsJson: string): string {
  return `// Generated by RunFlux. Dispatches connections using each node's declared activeOutput.
import { executeWorkflowGraph } from './runtime.js';
${imports.join('\n')}

interface GraphNode {
  id: string;
  name: string;
  isTrigger: boolean;
  outputs?: string[];
  run: (input: any, context?: any) => unknown | Promise<unknown>;
}
export const graphNodes: GraphNode[] = [
${graphNodesCode}
];
export const connections = ${connectionsJson};
export async function runWorkflow(payload: unknown = {}, triggerId?: string) {
  return executeWorkflowGraph(graphNodes, connections, payload, triggerId);
}
`;
}
