import type { PluginModule } from '@runflux/plugin-system/types';

/**
 * Log (004-core-nodes-catalog, RF-05): a deterministic, network-free output
 * fixture — passes the input through unchanged, giving a workflow an
 * observable end point without depending on an external HTTP endpoint being
 * available.
 */
export const manifest: PluginModule['manifest'] = {
  id: 'log-output',
  name: 'Log',
  category: 'output',
  version: '1.0.0',
  parameters: [{ name: 'label', label: 'Label', type: 'string', required: false, default: 'Log' }],
  supportedPlatforms: ['local', 'aws'],
};

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const label = JSON.stringify((nodeConfig.label as string | undefined) ?? 'Log');
    return {
      files: [
        {
          path: 'log-output.ts',
          content: `// Generated by RunFlux for plugin "log-output"
const LABEL = ${label};

export function run($json: any) {
  console.log('[log-output] ' + LABEL + ':', JSON.stringify($json, null, 2));
  return $json;
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const label = (params.label as string | undefined) ?? 'Log';
  console.log(`[log-output] ${label}:`, input);
  return input;
};
