import type { PluginModule } from '@runflux/plugin-system/types';
import { CONDITION_ROW_SCHEMA } from '@runflux/plugin-system/condition-row-schema';
import { matchRule, type ConditionRule } from '@runflux/plugin-system/operators';
import { STANDALONE_OPERATOR_CODE, STANDALONE_EXPRESSION_EVALUATOR_CODE } from '@runflux/plugin-system/snippets';

/**
 * If (004-core-nodes-catalog, RF-01): routes execution to one of two named
 * outputs ("true"/"false") depending on whether its configured conditions
 * match the node's input. Modeled after n8n's If node (packages/nodes-base/nodes/If).
 */
export const manifest: PluginModule['manifest'] = {
  id: 'condition-if',
  name: 'If',
  category: 'control-flow',
  version: '1.0.0',
  parameters: [
    { name: 'combinator', label: 'Combinator (and/or)', type: 'string', required: false, default: 'and' },
    { name: 'conditions', label: 'Conditions', type: 'json', required: true, default: [], rowSchema: CONDITION_ROW_SCHEMA },
  ],
  supportedPlatforms: ['local', 'aws'],
  outputs: ['true', 'false'],
};

export const generators: PluginModule['generators'] = {
  aws: (nodeConfig, ctx) => generators.local(nodeConfig, ctx),
  local: (nodeConfig) => {
    const conditions = JSON.stringify(Array.isArray(nodeConfig.conditions) ? nodeConfig.conditions : []);
    const combinator = JSON.stringify((nodeConfig.combinator as string | undefined) ?? 'and');
    return {
      files: [
        {
          path: 'condition-if.ts',
          content: `// Generated by RunFlux for plugin "condition-if"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

${STANDALONE_EXPRESSION_EVALUATOR_CODE}
${STANDALONE_OPERATOR_CODE}

export function run($json, context) {
  const $node = context?.$node || {};
  const $env = context?.$env || (typeof process !== 'undefined' ? process.env : {});
  const results = CONDITIONS.map((c) => compare(resolveValue(c.leftValue, $json, $node, $env), c.operator, resolveValue(c.rightValue, $json, $node, $env)));
  const matched = combine(results, COMBINATOR);
  return { value: $json, activeOutput: matched ? 'true' : 'false' };
}
`,
        },
      ],
      infra: [],
    };
  },
};

export const execute: PluginModule['execute'] = (params, input) => {
  const conditions = Array.isArray(params.conditions) ? (params.conditions as ConditionRule[]) : [];
  const combinator = (params.combinator as string | undefined) ?? 'and';
  const matched = matchRule(conditions, combinator);
  return { value: input, activeOutput: matched ? 'true' : 'false' };
};
