import { STANDALONE_EXPRESSION_EVALUATOR_CODE } from './snippets.js';
import { bundleStandalone } from './standalone.js';

const CONTEXT_CODE = bundleStandalone('@runflux/plugin-system/context-helpers', ['extractContext'], '__runfluxContext');
const EXPRESSION_CODE = CONTEXT_CODE + STANDALONE_EXPRESSION_EVALUATOR_CODE;
const CONDITION_CODE = EXPRESSION_CODE + bundleStandalone('@runflux/plugin-system/operators', ['matchRule'], '__runfluxConditions');
const SWITCH_CODE = EXPRESSION_CODE + bundleStandalone('@runflux/plugin-system/operators', ['evaluateSwitch'], '__runfluxSwitch');
const FIELDS_CODE = EXPRESSION_CODE + bundleStandalone('@runflux/plugin-system/fields-row-schema', ['composeFields'], '__runfluxFields');

export function generateConditionIfCode(config: { conditions?: unknown; combinator?: unknown }): string {
  const conditions = JSON.stringify(Array.isArray(config.conditions) ? config.conditions : []);
  const combinator = JSON.stringify((config.combinator as string | undefined) ?? 'and');

  return `// Generated by RunFlux for plugin "condition-if"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

${CONDITION_CODE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  const matched = matchRule(resolveValue(CONDITIONS, $json, $node, $env), COMBINATOR);
  return { value: $json, activeOutput: matched ? 'true' : 'false' };
}
`;
}

export function generateConditionSwitchCode(config: {
  rules?: unknown;
  fallbackEnabled?: unknown;
  ruleOutputs?: string[];
}): string {
  const defaultOutputs = ['output1', 'output2', 'output3', 'output4', 'output5'];
  const rules = JSON.stringify(Array.isArray(config.rules) ? config.rules : []);
  const fallbackEnabled = JSON.stringify(Boolean(config.fallbackEnabled));
  const ruleOutputs = JSON.stringify(config.ruleOutputs || defaultOutputs);

  return `// Generated by RunFlux for plugin "condition-switch"
const RULES = ${rules};
const FALLBACK_ENABLED = ${fallbackEnabled};
const RULE_OUTPUTS = ${ruleOutputs};

${SWITCH_CODE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  const activeOutput = evaluateSwitch(resolveValue(RULES, $json, $node, $env), RULE_OUTPUTS, FALLBACK_ENABLED);
  return { value: $json, activeOutput };
}
`;
}

export function generateFilterCode(config: { conditions?: unknown; combinator?: unknown }): string {
  const conditions = JSON.stringify(Array.isArray(config.conditions) ? config.conditions : []);
  const combinator = JSON.stringify((config.combinator as string | undefined) ?? 'and');

  return `// Generated by RunFlux for plugin "filter"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

${CONDITION_CODE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  const matched = matchRule(resolveValue(CONDITIONS, $json, $node, $env), COMBINATOR);
  return { value: $json, activeOutput: matched ? 'main' : null };
}
`;
}

export function generateSetCode(config: { fields?: unknown; includeOtherFields?: unknown }): string {
  const fields = JSON.stringify(Array.isArray(config.fields) ? config.fields : []);
  const includeOtherFields = JSON.stringify(Boolean(config.includeOtherFields));

  return `// Generated by RunFlux for plugin "set"
const FIELDS = ${fields};
const INCLUDE_OTHER_FIELDS = ${includeOtherFields};

${FIELDS_CODE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  return composeFields(resolveValue(FIELDS, $json, $node, $env), INCLUDE_OTHER_FIELDS && $json !== null && typeof $json === 'object' ? $json : {});
}
`;
}

export function generateHttpOutputCode(config: {
  method?: unknown;
  url?: unknown;
  headers?: unknown;
  body?: unknown;
}): string {
  const method = JSON.stringify((config.method as string | undefined) ?? 'GET');
  const url = JSON.stringify(config.url ?? '');
  const headers = JSON.stringify(config.headers ?? {});
  const body = JSON.stringify(config.body) ?? 'undefined';

  return `// Generated by RunFlux for plugin "http-output"
const METHOD = ${method};
const URL_TEMPLATE = ${url};
const HEADERS_TEMPLATE = ${headers};
const BODY_TEMPLATE = ${body};

${bundleStandalone('@runflux/plugin-system/http-client', ['callHttp'], '__runfluxHttp')}
${EXPRESSION_CODE}

export async function run($json, context) {
  const { $node, $env } = extractContext(context);
  const url = resolveValue(URL_TEMPLATE, $json, $node, $env);
  return callHttp(
    resolveValue(METHOD, $json, $node, $env), url,
    resolveValue(HEADERS_TEMPLATE, $json, $node, $env),
    resolveValue(BODY_TEMPLATE, $json, $node, $env), fetch,
  );
}
`;
}

export function generateCodeJavascriptCode(config: { code?: unknown }): string {
  const userCode = (config.code as string | undefined)?.trim() || 'return $json;';

  return `// Generated by RunFlux for plugin "code-javascript"
${CONTEXT_CODE}

export async function run($json: any, context?: any) {
  const { $node, $env } = extractContext(context);
  try {
    return await (async () => {
      ${userCode}
    })();
  } catch (error) {
    throw new Error('[code-javascript]: Execution error: ' + (error instanceof Error ? error.message : String(error)));
  }
}
`;
}

