import { STANDALONE_EXPRESSION_EVALUATOR_CODE, STANDALONE_OPERATOR_CODE } from './snippets.js';
import { bundleStandalone } from './standalone.js';

const STANDALONE_FIELDS_CODE = bundleStandalone('@runflux/plugin-system/fields-row-schema', ['normalizeFieldValue'], '__runfluxFields');

/**
 * Componentized Code Generators for RunFlux Plugins
 *
 * Provides standardized, professional code generation for compiled workflows.
 * Completely eliminates raw code string duplication and ad-hoc context handling in plugins.
 */

const STANDALONE_RUNTIME_PREAMBLE = `
${bundleStandalone('@runflux/plugin-system/context-helpers', ['extractContext'], '__runfluxContext')}

${STANDALONE_EXPRESSION_EVALUATOR_CODE}
${STANDALONE_OPERATOR_CODE}
${STANDALONE_FIELDS_CODE}

function evaluateConditions(conditions, combinator, $json, $node, $env) {
  const list = Array.isArray(conditions) ? conditions : [];
  if (list.length === 0) return true;
  const results = list.map((c) =>
    evaluateOperator(
      resolveValue(c.leftValue, $json, $node, $env),
      c.operator,
      resolveValue(c.rightValue, $json, $node, $env)
    )
  );
  return combineConditions(results, combinator);
}

function evaluateSwitchRules(rules, ruleOutputs, fallbackEnabled, $json, $node, $env) {
  const list = Array.isArray(rules) ? rules : [];
  for (let i = 0; i < list.length && i < ruleOutputs.length; i++) {
    const rule = list[i];
    if (evaluateConditions(rule?.conditions, rule?.combinator || 'and', $json, $node, $env)) {
      return ruleOutputs[i];
    }
  }
  return fallbackEnabled ? 'fallback' : null;
}

function composeSetFields(fields, includeOtherFields, $json, $node, $env) {
  const base = includeOtherFields && $json !== null && typeof $json === 'object' ? { ...$json } : {};
  const list = Array.isArray(fields) ? fields : [];
  for (const field of list) {
    if (field && typeof field.name === 'string') {
      base[field.name] = normalizeFieldValue(field, resolveValue(field.value, $json, $node, $env));
    }
  }
  return base;
}
`;

export function generateConditionIfCode(config: { conditions?: unknown; combinator?: unknown }): string {
  const conditions = JSON.stringify(Array.isArray(config.conditions) ? config.conditions : []);
  const combinator = JSON.stringify((config.combinator as string | undefined) ?? 'and');

  return `// Generated by RunFlux for plugin "condition-if"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

${STANDALONE_RUNTIME_PREAMBLE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  const matched = evaluateConditions(CONDITIONS, COMBINATOR, $json, $node, $env);
  return { value: $json, activeOutput: matched ? 'true' : 'false' };
}
`;
}

export function generateConditionSwitchCode(config: {
  rules?: unknown;
  fallbackEnabled?: unknown;
  ruleOutputs?: string[];
}): string {
  const defaultOutputs = ['output1', 'output2', 'output3', 'output4', 'output5'];
  const rules = JSON.stringify(Array.isArray(config.rules) ? config.rules : []);
  const fallbackEnabled = JSON.stringify(Boolean(config.fallbackEnabled));
  const ruleOutputs = JSON.stringify(config.ruleOutputs || defaultOutputs);

  return `// Generated by RunFlux for plugin "condition-switch"
const RULES = ${rules};
const FALLBACK_ENABLED = ${fallbackEnabled};
const RULE_OUTPUTS = ${ruleOutputs};

${STANDALONE_RUNTIME_PREAMBLE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  const activeOutput = evaluateSwitchRules(RULES, RULE_OUTPUTS, FALLBACK_ENABLED, $json, $node, $env);
  return { value: $json, activeOutput };
}
`;
}

export function generateFilterCode(config: { conditions?: unknown; combinator?: unknown }): string {
  const conditions = JSON.stringify(Array.isArray(config.conditions) ? config.conditions : []);
  const combinator = JSON.stringify((config.combinator as string | undefined) ?? 'and');

  return `// Generated by RunFlux for plugin "filter"
const CONDITIONS = ${conditions};
const COMBINATOR = ${combinator};

${STANDALONE_RUNTIME_PREAMBLE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  const matched = evaluateConditions(CONDITIONS, COMBINATOR, $json, $node, $env);
  return { value: $json, activeOutput: matched ? 'main' : null };
}
`;
}

export function generateSetCode(config: { fields?: unknown; includeOtherFields?: unknown }): string {
  const fields = JSON.stringify(Array.isArray(config.fields) ? config.fields : []);
  const includeOtherFields = JSON.stringify(Boolean(config.includeOtherFields));

  return `// Generated by RunFlux for plugin "set"
const FIELDS = ${fields};
const INCLUDE_OTHER_FIELDS = ${includeOtherFields};

${STANDALONE_RUNTIME_PREAMBLE}

export function run($json, context) {
  const { $node, $env } = extractContext(context);
  return composeSetFields(FIELDS, INCLUDE_OTHER_FIELDS, $json, $node, $env);
}
`;
}

export function generateHttpOutputCode(config: {
  method?: unknown;
  url?: unknown;
  headers?: unknown;
  body?: unknown;
}): string {
  const method = JSON.stringify((config.method as string | undefined) ?? 'GET');
  const url = JSON.stringify(config.url ?? '');
  const headers = JSON.stringify(config.headers ?? {});
  const body = JSON.stringify(config.body) ?? 'undefined';

  return `// Generated by RunFlux for plugin "http-output"
const METHOD = ${method};
const URL_TEMPLATE = ${url};
const HEADERS_TEMPLATE = ${headers};
const BODY_TEMPLATE = ${body};

${bundleStandalone('@runflux/plugin-system/http-client', ['callHttp'], '__runfluxHttp')}
${STANDALONE_RUNTIME_PREAMBLE}

export async function run($json, context) {
  const { $node, $env } = extractContext(context);
  const url = resolveValue(URL_TEMPLATE, $json, $node, $env);
  if (typeof url !== 'string' || url.trim() === '') {
    throw new Error('http-output: "url" is empty or invalid');
  }
  return callHttp(
    resolveValue(METHOD, $json, $node, $env), url,
    resolveValue(HEADERS_TEMPLATE, $json, $node, $env),
    resolveValue(BODY_TEMPLATE, $json, $node, $env), fetch,
  );
}
`;
}

export function generateCodeJavascriptCode(config: { code?: unknown }): string {
  const userCode = (config.code as string | undefined)?.trim() || 'return $json;';

  return `// Generated by RunFlux for plugin "code-javascript"
${STANDALONE_RUNTIME_PREAMBLE}

export async function run($json: any, context?: any) {
  const { $node, $env } = extractContext(context);
  try {
    return await (async () => {
      ${userCode}
    })();
  } catch (error) {
    throw new Error('[code-javascript]: Execution error: ' + (error instanceof Error ? error.message : String(error)));
  }
}
`;
}

